name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*


jobs:
- template: templates/testing_job.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-latest'

- template: templates/testing_job.yml
  parameters:
    name: macOS
    vmImage: 'macOS-latest'

- template: templates/testing_job.yml
  parameters:
    name: Windows
    vmImage: 'windows-latest'


schedules:
- cron: "0 4 1 * *"
  displayName: Monthly build
  branches:
    include:
    - main
  always: true
