# build documentation (PDF & HTML)
trigger:
  tags:
    include:
      - v*

pr: none

pool:
  vmImage: "ubuntu-latest"

container: sphinxdoc/sphinx-latexpdf:latest

steps:
  - script: python --version
    displayName: "Check Python version"

  - script: |
      apt-get update
      apt-get install -y build-essential
    displayName: "Install C compiler"

  - script: |
      python -m pip install --upgrade pip
      pip install numpy scipy h5py
    displayName: "Install build dependencies"

  - script: |
      pip install matplotlib numpydoc sphinx sphinx-pyproject sphinx_rtd_theme
    displayName: "Install documentation dependencies"

  - script: pip install .
    displayName: "Install xrayutilities"

  - script: |
      sphinx-apidoc -f -o doc/source lib/xrayutilities
    displayName: "Generating API documentation"

  - script: |
      sphinx-build -b html doc/source build/sphinx/html
    displayName: "Generating HTML documentation"

  - script: |
      # copy to allow regeneration of the patch
      cp build/sphinx/html/index.html build/sphinx/html/index.html.orig
      patch -p0 < doc/webpage.patch
      # in case its needed, update the patch locally using this command
      # diff -Naur build/sphinx/html/index.html.orig build/sphinx/html/index.html > doc/webpage.patch
    continueOnError: true
    displayName: "Patch HTML documentation for webpage"

  - script: |
      sphinx-build -b latex doc/source build/sphinx/latex
      make -C build/sphinx/latex
      cp build/sphinx/latex/xrayutilities.pdf build/sphinx/html/
    displayName: "Generating PDF documentation"

  # cleanTargetFolder not supported without shell access
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: "web.sourceforge.net"
      sourceFolder: "build/sphinx/html"
      contents: "**"
      targetFolder: "/home/project-web/xrayutilities/htdocs"
      cleanTargetFolder: false
      readyTimeout: "20000"
      failOnEmptySource: true
    displayName: "Publish documentation to sourceforge"
