# trigger build only after successful test on master
resources:
  pipelines:
  - pipeline: tox-testing
    source: tox-testing
    trigger:
      branches:
        include:
        - master
        - refs/tags/v*

trigger: none
pr: none

variables:
  CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
  CIBW_BEFORE_BUILD: pip install numpy scipy h5py
  CIBW_SKIP: "*-win32 *-manylinux_i686"

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-20.04'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel
        pip3 install twine
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: TwineAuthenticate@0
      inputs:
        artifactFeeds: 'xrayutilities-dev'
    - script: 'twine upload -r xrayutilities-dev --config-file $(PYPIRC_PATH) wheelhouse'

- job: macos
  pool: {vmImage: 'macOS-10.15'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel
        pip3 install twine
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: TwineAuthenticate@0
      inputs:
        artifactFeeds: 'xrayutilities-dev'
    - script: 'twine upload -r xrayutilities-dev --config-file $(PYPIRC_PATH) wheelhouse'

- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python -m pip install --upgrade pip
        pip install cibuildwheel
        pip install twine
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: TwineAuthenticate@0
      inputs:
        artifactFeeds: 'xrayutilities-dev'
    - script: 'twine upload -r xrayutilities-dev --config-file $(PYPIRC_PATH) wheelhouse'