# build documentation (PDF & HTML)
trigger:
  tags:
    include:
      - v*

pr: none

variables:
  python_version: 3.10

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python_version)'
  displayName: 'Use Python $(python_version)'

- script: |
    python -m pip install --upgrade pip
    pip install numpy scipy h5py
  displayName: 'Install build dependencies'

- script: |
    pip install matplotlib numpydoc rst2pdf sphinx sphinx_rtd_theme svglib
  displayName: 'Install documentation dependencies'

- script: pip install .
  displayName: 'Install xrayutilities'

- script: |
    sphinx-apidoc -f -o doc/source lib/xrayutilities
  displayName: 'Generating API documentation'

- script: |
    python setup.py build_doc -b html
  displayName: 'Generating HTML documentation'

- script: |
    # copy to allow regeneration of the patch
    cp build/sphinx/html/index.html build/sphinx/html/index.html.orig
    patch -p0 < doc/webpage.patch
    # in case its needed, update the patch locally using this command
    # diff -Naur build/sphinx/html/index.html.orig build/sphinx/html/index.html > doc/webpage.patch
  continueOnError: true
  displayName: 'Patch HTML documentation for webpage'

- script: |
    python setup.py build build_doc -b pdf
    cp build/sphinx/pdf/xrayutilities.pdf build/sphinx/html/
  displayName: 'Generating PDF documentation'

# cleanTargetFolder not supported without shell access
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'web.sourceforge.net'
    sourceFolder: 'build/sphinx/html'
    contents: '**'
    targetFolder: '/home/project-web/xrayutilities/htdocs'
    cleanTargetFolder: false
    readyTimeout: '20000'
    failOnEmptySource: true
  displayName: 'Publish documentation to sourceforge'
