
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  srcDirectory: lib
  testsDirectory: tests
  examplesDirectory: examples

steps:
- script: pip install pylint flake8 flake8-pyproject
  displayName: Install packages for linting

- script: find $(srcDirectory) $(testsDirectory) -type f -name "*.py" | xargs pylint
  displayName: Linting: pylint

- script: flake8 $srcDirectory $testsDirectory $examplesDirectory
  displayName: Linting: flake8
