name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
    branches:
        include:
            - main
    tags:
        include:
            - v*

jobs:
    - job:
      displayName: "Linting"
      pool:
          vmImage: "ubuntu-latest"
      variables:
          srcDirectory: lib
          testsDirectory: tests
          examplesDirectory: examples
      steps:
          - task: UsePythonVersion@0
            inputs:
                versionSpec: "3.13"
          - script: pip install -r recommended_requirements.txt
            # needed to help pylint analyze our code
            displayName: "Install package requirements"

          - script: pip install -v .
            # need to install in order to generate C-extension
            displayName: "Install xrayutilities"

          - script: pip install pylint flake8 flake8-pyproject
            displayName: "Install packages for linting"

          - script: pylint xrayutilities
            displayName: "Linting: pylint"
            continueOnError: true

          - script: flake8 $(srcDirectory) $(testsDirectory) $(examplesDirectory)
            displayName: "Linting: flake8"

    - template: templates/testing_job.yml
      parameters:
          name: "Linux"
          vmImage: "ubuntu-latest"

    - template: templates/testing_job.yml
      parameters:
          name: "macOS"
          vmImage: "macOS-latest"

    - template: templates/testing_job.yml
      parameters:
          name: "Windows"
          vmImage: "windows-latest"

schedules:
    - cron: "0 4 1 * *"
      displayName: Monthly build
      branches:
          include:
              - main
      always: true
