# build 
trigger: none

variables:
  python_version: 3.8

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python_version)'
  displayName: 'Use Python $(python_version)'

- script: |
    python -m pip install --upgrade pip
    pip install numpy scipy h5py
  displayName: 'Install build dependencies'

- script: |
    pip install numpydoc rst2pdf sphinx
  displayName: 'Install documentation dependencies'

- script: |
    sphinx-apidoc -f -o doc/source lib/xrayutilities
  displayName: 'Generating API documentation'

- script: |
    python setup.py build build_doc -b pdf
  displayName: 'Generating PDF documentation'

- script: |
    python setup.py build_doc -b html
    patch -p0 < doc/webpage.patch
  displayName: 'Generating HTML documentation'

- task: PublishBuildArtifacts@1
  inputs: {pathtoPublish: 'build/sphinx/pdf/xrayutilities.pdf'}
  displayName: 'Publish PDF documentation'
