name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

# trigger build only after successful linting
resources:
  pipelines:
  - pipeline: linting
    source: linting

pr: none

jobs:
- template: templates/testing_job.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-latest'

- template: templates/testing_job.yml
  parameters:
    name: macOS
    vmImage: 'macOS-latest'

- template: templates/testing_job.yml
  parameters:
    name: Windows
    vmImage: 'windows-latest'


schedules:
- cron: "0 4 1 * *"
  displayName: Monthly build
  branches:
    include:
    - main
  always: true
