import os

#set the sources
Import("env")

env = Environment()
sphinx = Tool('sphinx4scons')
sphinx(env)

#env.Environment(tools=['sphinx4scons'])
html = env.Sphinx('html','source',builder='html')
patchcss = env.Command(None,['css.patch'],'cd doc; patch -p0 < css.patch')
env.Alias("html", html)
env.Alias("css",patchcss)
AlwaysBuild(patchcss)

latex = env.Sphinx('latex','source',builder='latex')
env.Alias("latex", latex)
pdf = env.Command('../xrayutilities.pdf',['latex/xrayutilities.tex'],'cd doc/latex; make; mv $TARGET ../..; cd ../..')
env.Alias("pdf", pdf)
