#set the sources
Import("env")

#compile the shared library - default behavior
sources = ["gridder.c","qconversion.c","vecmat3.c","rot_matrix.c","block_average.c"]
objects_env = env.SharedObject(sources)
lib = env.SharedLibrary("xrutils",objects_env)
Default(lib)

#install the library
env.Install("$PREFIX/lib",lib)
