import os

# Install user manual
manual = "xrayutilities.pdf"

Import("env")

if os.sys.platform in ["darwin","linux2"]:
    Command("dummy","dummy",[Mkdir(os.path.join(env['DESTDIRPREFIX'],"share","doc","xrayutilities"))])
    Alias("install",env.Install(os.path.join(env['DESTDIRPREFIX'],"share","doc","xrayutilities"),manual))
elif "win" in os.sys.platform:
    Command("dummy","dummy",[Mkdir(os.path.join(env['PREFIX'],"share","doc","xrayutilities"))])
    Alias("install",env.Install(os.path.join(env['PREFIX'],"share","doc","xrayutilities"),manual))
