"""
xrutils derives its own exceptions which are raised 
upon wrong input when calling one of xrutils functions.
none of the pre-defined exceptions is made for that purpose.
"""

# other used Exception should mainly be the python built-in exceptions
#
# * TypeError
#  Raised when an operation or function is applied to an object of inappropriate type
#
# * ValueError
#  Raised when a operation or function receives an argument that 
#  has the right type but an inappropriate value
#
# * UserWarning
#   Base class for warnings generated by user code


class InputError(Exception):
    """
    Exception raised for errors in the input.
    Either wrong datatype not handled by TypeError or missing mandatory 
    keyword argument (Note that the obligation to give keyword arguments 
    might depend on the value of the arguments itself)
    
    Attibutes
        expr -- input expression in which the error occurred
        msg  -- explanation of the error
    """

    def __init__(self, msg):
        self.msg = msg

    def __str__(self):
        return self.msg

